[package]
name = "zzhack"
version = "0.1.0"
authors = ["youncccat <mist@zzhack.fun>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]
wasm-opt = false

[dependencies]
yew = "0.18.0"
wasm-bindgen = "0.2.67"
material-yew = { git = "https://github.com/hamza1311/material-yew", features = ["full"] }
yew-router = "0.15.0"
stdweb = "0.4.20"
css-in-rust = "0.5.0"
web-sys = "0.3.51"
