[package]
name = "zzhack"
version = "0.1.0"
authors = ["youncccat <1306036576@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]
wasm-opt = false

[dependencies]
yew = "0.17"
wasm-bindgen = "0.2.67"